---
title: EETER
timezone: Europe/Tallinn
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  services:
    title: Services
    output: true
  team-members:
    title: Team Members
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
    Heading: 
- scope:
    path: ''
    type: projects
  values:
    layout: project
    Subheading: 
    Intro: 
    Extra Information: 
    Featured Image: 
    Menu Hover Image: 
    Is Coming Soon: 
- scope:
    path: ''
    type: services
  values:
    layout: service
    Subheading: 
    Projects: 
    Image: 
- scope:
    path: ''
    type: team-members
  values:
    layout: team-member
    Role: 
    Linkedin: 
    Github: 
    Medium: 
    Dribbble: 
    Behance: 
    Image: 
permalink: pretty
